version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis

  webserver:
    image: nginx:latest
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    ports:
      - "27017-27018:27017"

  redis:
    image: redis:latest
    ports:
      - "6379-6385:6379"
